#! /usr/bin/env python
# -*- coding: utf-8 -*-
# Author: Xuchao


#这是第一四修改
print('sjkhj')
print('sjkhj')
print('sjkhj')
print('sjkhj')
print('sjkhj')
print('sjkhj')
print('sjkhj')
print('sjkhj')
print('sjkhj')
print('sjkhj')
print('sjkhj')
print('sjkhj')
print('sjkhj')
print('sjkhj')
print('sjkhj')
print('sjkhj')
print('sjkhj')
print('sjkhj')
print('sjkhj')
print('sjkhj')
print('sjkhj')
print('sjkhj')
print('sjkhj')
print('sjkhj')
print('sjkhj')
print('sjkhj')
print('sjkhj')
print('sjkhj')
print('sjkhj')
print('sjkhj')
print('sjkhj')
print('sjkhj')
print('sjkhj')
print('sjkhj')
print('sjkhj')
print('sjkhj')
print('sjkhj')
print('sjkhj')